#!/usr/bin/env python3
"""Generates Android strings.xml files from i18n/mobile/<lang>.json.

en.json is the source of truth (it becomes values/strings.xml, the fallback);
a missing key in another language falls back to English at runtime.
Run from anywhere: python3 i18n/gen.py
"""
import json
import os
import re
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "app", "src", "main", "res")

# JSON file name -> Android resource qualifier.
QUALIFIER = {"en": "", "zh-CN": "zh-rCN", "zh-TW": "zh-rTW", "pt-BR": "pt-rBR"}


def android_escape(s):
    s = escape(s)
    s = s.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")
    if s.startswith("@") or s.startswith("?"):
        s = "\\" + s
    return s


def main():
    base = json.load(open(os.path.join(HERE, "mobile", "en.json"), encoding="utf-8"))
    langs = sorted(f[:-5] for f in os.listdir(os.path.join(HERE, "mobile")) if f.endswith(".json"))
    for lang in langs:
        data = json.load(open(os.path.join(HERE, "mobile", lang + ".json"), encoding="utf-8"))
        unknown = set(data) - set(base)
        assert not unknown, f"{lang}: keys not in en.json: {sorted(unknown)}"
        for k, v in data.items():
            want = sorted(re.findall(r"%\d\$[sd]", base[k]))
            got = sorted(re.findall(r"%\d\$[sd]", v))
            assert want == got, f"{lang}.{k}: placeholders {got} != {want}"
        qual = QUALIFIER.get(lang, lang)
        folder = os.path.join(RES, "values" + ("-" + qual if qual else ""))
        os.makedirs(folder, exist_ok=True)
        lines = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by i18n/gen.py from i18n/mobile/%s.json; edit that instead. -->" % lang, "<resources>"]
        if lang == "en":
            lines.append('    <string name="app_name" translatable="false">AsenaScale Mobile</string>')
        for k in base:
            if k in data:
                lines.append('    <string name="%s">%s</string>' % (k, android_escape(data[k])))
        lines.append("</resources>")
        open(os.path.join(folder, "strings.xml"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
        # Older Android versions look up Indonesian under its legacy code.
        if lang == "id":
            legacy = os.path.join(RES, "values-in")
            os.makedirs(legacy, exist_ok=True)
            open(os.path.join(legacy, "strings.xml"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    # Per-app language picker (Android 13+).
    locales = ["en"] + [l for l in langs if l != "en"]
    xml = ['<?xml version="1.0" encoding="utf-8"?>', '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">']
    xml += ['    <locale android:name="%s"/>' % l for l in locales]
    xml.append("</locale-config>")
    os.makedirs(os.path.join(RES, "xml"), exist_ok=True)
    open(os.path.join(RES, "xml", "locales_config.xml"), "w", encoding="utf-8").write("\n".join(xml) + "\n")
    print("generated", len(langs), "languages:", " ".join(langs))
    desktop()


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def desktop():
    """i18n/desktop/<lang>.json -> host/src/i18n_table.rs (compiled in)."""
    src = os.path.join(HERE, "desktop")
    base = json.load(open(os.path.join(src, "en.json"), encoding="utf-8"))
    keys = list(base)
    langs = ["en"] + sorted(f[:-5] for f in os.listdir(src) if f.endswith(".json") and f != "en.json")
    out = ["// Generated by i18n/gen.py from i18n/desktop/*.json; edit those instead.", "",
           "pub const KEYS: &[&str] = &[" + ", ".join(rust_str(k) for k in keys) + "];", "",
           "/// (language, texts in KEYS order; empty = use English).",
           "pub const LANGS: &[(&str, &[&str])] = &["]
    for lang in langs:
        data = json.load(open(os.path.join(src, lang + ".json"), encoding="utf-8"))
        unknown = set(data) - set(base)
        assert not unknown, f"desktop {lang}: keys not in en.json: {sorted(unknown)}"
        for k, v in data.items():
            assert sorted(re.findall(r"\{\w+\}", v)) == sorted(re.findall(r"\{\w+\}", base[k])), f"desktop {lang}.{k}: placeholders"
        out.append("    (%s, &[" % rust_str(lang))
        for k in keys:
            out.append("        %s," % rust_str(data.get(k, "")))
        out.append("    ]),")
    out.append("];")
    open(os.path.join(HERE, "..", "host", "src", "i18n_table.rs"), "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("desktop:", len(langs), "languages")


if __name__ == "__main__":
    main()
